version: "3.7"
services:
  app:
    build:
      args:
        user: thony
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: avia-starter
    container_name: avia-starter-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - avia-starter-net

  nginx:
    image: nginx:latest
    container_name: avia-starter-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - avia-starter-net

networks:
  avia-starter-net:
    driver: bridge
